In [1]:
import pylls 
import numpy as np
import importlib
from typing import Tuple


In [2]:
importlib.reload(pylls)

<module 'pylls' from '/Users/theo/Documents/PROJET/pylls/pylls/__init__.py'>

In [5]:
weights = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
biais = np.array([1, 1, 1])

In [15]:
np.log(weights)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [4]:
def _broadcasted_axis(old_shape, new_shape: Tuple[int, ...]) -> Tuple[int, ...]:
    """
    Return a tuple of the axis to be broadcasted, useful for the sum over those axis during backprop.

    ex : 
        old_shape = (3,)
        new_shape = (2, 2, 3)
        returns (0, 1)
    """
    augmented_shape = (1,) * (len(new_shape) - len(old_shape)) + old_shape
    return tuple([i for i in range(len(new_shape)) if new_shape[i] > augmented_shape[i]])



In [12]:
axis = _broadcasted_axis((2, 2, 3), (2, 2, 3))

In [13]:
axis

()

In [11]:
np.sum(weights, axis=())

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
weights + biais

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [2]:
weightsTensor = pylls.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], requires_grad=True)
biaisTensor = pylls.Tensor([1, 2, 3], requires_grad=True)

In [3]:
test = pylls.Tensor(2)

In [4]:
test.requires_grad

False

In [5]:
test.backprop()

AssertionError: grad not computed, not activated

In [6]:
with pylls.no_grad():
    """
    print(pylls.Tensor.gradient_enabled)
    print(weightsTensor.gradient_enabled)
    print(biaisTensor.gradient_enabled)
    """
    result = weightsTensor + biaisTensor
    print(result.gradient_enabled)


False


In [7]:
result.requires_grad

False

In [8]:
result.backprop()

AssertionError: grad not computed, not activated

In [17]:
a = True
b = False
if a and b:
    print('yes')
else : 
    print('no')

no


In [11]:
result.backprop()

In [14]:
result.gradient_enabled

True

In [9]:
pylls.Tensor.gradient_enabled

True

In [11]:
weightsTensor.gradient_enabled

False

In [10]:
biaisTensor.gradient_enabled

False

In [9]:
pylls.Tensor.gradient_enabled = False

In [4]:
weightsTensor.data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
weightsTensor.test()

ui


In [4]:
weightsTensor.data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
result = weightsTensor + biaisTensor

In [6]:
result.data

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [7]:
result.backprop()

In [8]:
result.grad

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
result._zero_grad()

In [11]:
result.children[0].grad

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
result.children[1].grad

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
weightsTensor.grad

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
biaisTensor.grad

array([3, 3, 3])

In [13]:
arr

array([1, 2])

In [18]:
check = pylls.Tensor(arr)

In [20]:
check

Tensor([[1 2]
 [4 5]])

In [26]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [27]:
aNew = a[:, np.newaxis]

In [23]:
a

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [30]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [29]:
aTensor = pylls.Tensor(a)
aNewTensor = pylls.Tensor(aNew)
bTensor = pylls.Tensor(b)

In [41]:
aTensor.data.shape

(4,)

In [36]:
a = np.array([[1, 2, 3, 4, 5, 6]])
c = np.array([1, 2, 3])
print(a.shape, c.shape)

(1, 6) (3,)


In [107]:
test = np.array([[[1, 2, 2], 
                 [3, 4, 2]],

                 [[1, 2, 2], 
                  [3, 4, 2]],

                  [[1, 2, 2], 
                  [3, 4, 2]]])

In [118]:
3 ** -1

0.3333333333333333

In [99]:
def test(left, right):
    ldim = len(left)
    rdim = len(right)
    maxdim = max(ldim, rdim)

    lshape_new = (1, ) * (maxdim - ldim) + left
    rshape_new = (1, ) * (maxdim - rdim) + right
    return lshape_new, rshape_new

In [88]:
def broadcasted_axis(old_shape, new_shape):
    augmented_shape = (1,) * (len(new_shape) - len(old_shape)) + old_shape
    return tuple([i for i in range(len(new_shape)) if new_shape[i] > augmented_shape[i]])

In [100]:
ui, non = test((3,) , (2, 3, 3))
broadcasted_axis((2, 3, 3), (2, 3, 3))

()

In [102]:
np.array([1, 2, 3]) + 2

array([3, 4, 5])

In [83]:
ui[0]

1

In [80]:
tuple([i for i in [1, 2, 3, 4]])

(1, 2, 3, 4)

In [43]:
test.sum()

10

In [49]:
test.sum(axis=(0,))

array([4, 6])