In [9]:
import pylls 
import numpy as np

In [17]:
arr = np.array([[1, 2, 4]])

In [13]:
arr

array([1, 2])

In [18]:
check = pylls.Tensor(arr)

In [20]:
check

Tensor([[1 2]
 [4 5]])

In [26]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [27]:
aNew = a[:, np.newaxis]

In [23]:
a

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [30]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [29]:
aTensor = pylls.Tensor(a)
aNewTensor = pylls.Tensor(aNew)
bTensor = pylls.Tensor(b)

In [41]:
aTensor.data.shape

(4,)

In [36]:
a = np.array([[1, 2, 3, 4, 5, 6]])
c = np.array([1, 2, 3])
print(a.shape, c.shape)

(1, 6) (3,)


In [107]:
test = np.array([[[1, 2, 2], 
                 [3, 4, 2]],

                 [[1, 2, 2], 
                  [3, 4, 2]],

                  [[1, 2, 2], 
                  [3, 4, 2]]])

In [118]:
3 ** -1

0.3333333333333333

In [99]:
def test(left, right):
    ldim = len(left)
    rdim = len(right)
    maxdim = max(ldim, rdim)

    lshape_new = (1, ) * (maxdim - ldim) + left
    rshape_new = (1, ) * (maxdim - rdim) + right
    return lshape_new, rshape_new

In [88]:
def broadcasted_axis(old_shape, new_shape):
    augmented_shape = (1,) * (len(new_shape) - len(old_shape)) + old_shape
    return tuple([i for i in range(len(new_shape)) if new_shape[i] > augmented_shape[i]])

In [100]:
ui, non = test((3,) , (2, 3, 3))
broadcasted_axis((2, 3, 3), (2, 3, 3))

()

In [102]:
np.array([1, 2, 3]) + 2

array([3, 4, 5])

In [83]:
ui[0]

1

In [80]:
tuple([i for i in [1, 2, 3, 4]])

(1, 2, 3, 4)

In [43]:
test.sum()

10

In [49]:
test.sum(axis=(0,))

array([4, 6])